### ISSUE TITLE
SyntaxError: unexpected EOF while parsing

### ISSUE THREAD

**Issue by claflico** [miketuckman/TabloExtract#3]
Using same VM that was working before (I've created a separate account for personal vs work). CentOS 7, python2.7.  I have power-cycled my tablo to stop any live tv streams. 

Tablo Device: 2.1.16
HTML Application: 0.9.323

[root@centos ~]# ./TabloToGo.v1.py -db:tablo/tablo2go.db -tablo:IP_ADDR -ffmpeg:/usr/bin/ffmpeg -output:/mnt/nfs/tablo/ -temp:/tmp -list
Traceback (most recent call last):
  File "./TabloToGo.v1.py", line 436, in <module>
    DB, found_count, add_count, del_count, proc_count = db_update(TABLOS, DB)
  File "./TabloToGo.v1.py", line 231, in db_update
    DB[IP][ID] = get_meta(IP, ID)
  File "./TabloToGo.v1.py", line 91, in get_meta
    metadata = eval(metadata)
  File "<string>", line 0

```
^
```

SyntaxError: unexpected EOF while parsing

Any ideas?

**Comment by prconnor** [comment]
I have the same result today.  I have previously successfully run this script.  My router shows the tablo still connected at the same IP address, and the tablo is accessible via web interface without observable issues.

eee@eee-B202:~/bin$ ./tablo2go.py -db:tablo2go.db -tablo:IP_ADDR -ffmpeg:ffmpeg -output:/home/eee/Videos/TV -temp:/home/tmp -list
Traceback (most recent call last):
  File "./tablo2go.py", line 436, in <module>
    DB, found_count, add_count, del_count, proc_count = db_update(TABLOS, DB)
  File "./tablo2go.py", line 231, in db_update
    DB[IP][ID] = get_meta(IP, ID)
  File "./tablo2go.py", line 91, in get_meta
    metadata = eval(metadata)
  File "<string>", line 0

```
^
```

SyntaxError: unexpected EOF while parsing

**Comment by arejay73** [comment]
I am getting this error as well.  I have run this script for almost 90 days 24/7 with no errors.  No all of a sudden I am getting this error.

Traceback (most recent call last):
  File "./TabloToGo.v1.py", line 436, in <module>
    DB, found_count, add_count, del_count, proc_count = db_update(TABLOS, DB)
  File "./TabloToGo.v1.py", line 231, in db_update
    DB[IP][ID] = get_meta(IP, ID)
  File "./TabloToGo.v1.py", line 91, in get_meta
    metadata = eval(metadata)
  File "<string>", line 0

```
^
```

SyntaxError: unexpected EOF while parsing
